### ISSUE TITLE
technical page

### ISSUE THREAD

**Issue by pacharanero** [open-health-hub/nhsbuntu#15]
tech specs and info

- base distro
- kernel info
- desktop environment
- package list

**Comment by crabcrabcam** [comment]
I've started working on this but I'm not quite sure where to find the information for it. So far I have added the technical details to the bottom of the `About` page. 
![screenshot from 2017-05-12 20-44-09](https://cloud.githubusercontent.com/assets/13933264/26014291/d1ad9310-3753-11e7-8c6f-69d389a953fa.png)

Where can I get more information about the packages and that sort of thing and is that sort of design alright or do you want it on a new page? I tried adding a new page and failed because I couldn't get Jekyll to see it (I've never used it before and really can't work it out. If you could help that would be great)

My fork is [here](https://github.com/crabcrabcam/www.nhsbuntu.org)

**Comment by robdyke** [comment]
Thanks @crabcrabcam.

Would you be able to create a new page rather than add to the About? 

Also, NHSbuntu is based on Ubuntu 16.04, not 14.04

We don't include Chrome, however we do provide scripts to install it.

**Comment by crabcrabcam** [comment]
I've moved it to a new page and changed the information to as much as I know. Do you have any of this information that you could send me so I can add it in?

I added an "Extra Details" section so the first part can just be bullet points and a "Hardware Specifications" part for the min and recommended requirements. 

I added the link in the bottom section.

![screenshot from 2017-05-13 15-07-11](https://cloud.githubusercontent.com/assets/13933264/26026154/53c162c4-37ee-11e7-9d64-83692f7e8aa1.png)
![screenshot from 2017-05-13 15-07-45](https://cloud.githubusercontent.com/assets/13933264/26026156/561fa0d0-37ee-11e7-8d8f-189d9b70845f.png)
![screenshot from 2017-05-13 15-09-14](https://cloud.githubusercontent.com/assets/13933264/26026158/5ac0c560-37ee-11e7-962a-5f18c7810585.png)

(The blue on the screenshots isn't really there it's just because gnome-screenshot is broken on my PC)

Hope this is alright, Cameron. :)

**Comment by Mraanderson** [comment]
$ apt list --installed > installed.txt

That'll be a starting point.

**Comment by robdyke** [comment]
See https://www.nhsbuntu.org/development/2017/06/19/making-nhsbuntu/
