### ISSUE TITLE
LibreOffice version is old

### ISSUE THREAD

**Issue by jimhaddon** [open-health-hub/nhsbuntu#41]
The version of LibreOffice included in NHSbuntu is quite old meaning the skin looks old fashioned. Are we able to uplift the version included/available in the repo?

**Comment by pacharanero** [comment]
Almost certainly possible either by finding a more up to date PPA or by making our own Packagecloud.

@robdyke options?

**Comment by awilkins** [comment]
There's a LibreOffice packaging team with a slew of PPAs 

https://launchpad.net/~libreoffice/+archive/ubuntu/ppa

**Comment by awilkins** [comment]
Worth noting that the age of the release isn't necessarily the problem - see screenshot.

Upper pair of windows is LibreOffice Writer on NHSBuntu, lower pair is the same on my desktop install which is vanilla Ubuntu 16.04 (NHSBuntu is based on 16.04).

Both versions of LibreOffice are identical (5.1), but it looks like Ubuntu Unity includes a "not looking like ass" theme that Ubuntu GNOME lacks.

![image](https://user-images.githubusercontent.com/368399/27743340-99804916-5db3-11e7-9962-8d6985c08288.png)

Undaunted by this, installed LibreOffice 5.3 in NHSBuntu from the PPA mentioned above.

After? Still looks like ass.

![image](https://user-images.githubusercontent.com/368399/27743772-0131a374-5db5-11e7-8caf-40e09e8c3438.png)

Default style in Ubuntu is "Breeze". Default style in NHSBuntu is "Tango".

Here's the generic default "Galaxy"

![image](https://user-images.githubusercontent.com/368399/27743999-d4679942-5db5-11e7-98f7-21993b0d94de.png)

"Breeze" and a number of others are available in the repo (`libreoffice-style-*` packages). Here's the newer shinier 5.3 Breeze in NHSBuntu

![image](https://user-images.githubusercontent.com/368399/27744125-4ad7d04c-5db6-11e7-897a-f560cc0cdd53.png)

Also worth noting that in the grand scheme of things : I'd be surprised if there was heavy uptake of NHSBuntu before next April, which is the date of the next LTS release of the base distro, and will include whatever is the mainstream release of LibreOffice at the time.

The use of "breeze" is defined in LibreOffice core on detecting Unity (or OSX, or KDE5)  as a desktop : see [patch](https://cgit.freedesktop.org/libreoffice/core/commit/?id=c0da1080b61a1d51654fc34fdaeba373226065ff).

You can't remove `libreoffice-style-galaxy` (the most ass-looking one and the fallback if Tango is absent) because it's a dependency of the core packages.

So the only ways to fix this are to i) Use Unity (which won't be around in 18.04) or ii) fix the config

You can fix the default style for new users by imposing LibreOffice config on them in their default home folder : 

https://askubuntu.com/questions/749849/how-do-i-set-the-libreoffice-icon-style-for-new-users

https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1569968

**Comment by pacharanero** [comment]
Awesome info @awilkins 

Option ii) fix the config is not a problem to do with livebuild.

I would vote we slate this work for one of the next work packages, since 'Libre Office Looking Like Ass' does feature highly in the feedback we get from users and would-be users.

**Comment by pacharanero** [comment]
PPAs to use:

`deb http://ppa.launchpad.net/libreoffice/ppa/ubuntu xenial main`
`deb-src http://ppa.launchpad.net/libreoffice/ppa/ubuntu xenial main`

also the best theme is indeed the one suggested by @awilkins above
`sudo apt install libreoffice-style-breeze`
